### ISSUE TITLE
demo app

### ISSUE THREAD

**Issue by lduboeuf** [c-smile/spapp#11]
hello, really nice work. I indeed found a MVC library that keep your code clean and simple to understand. Feel free to add my app as a demo: https:

**Comment by lduboeuf** [comment]
https://lduboeuf.github.io/team-tool-box

**Comment by lduboeuf** [comment]
source can be found here: https://github.com/lduboeuf/team-tool-box

**Comment by c-smile** [comment]
Thanks, Lionel. I've added reference to your nice application as an example.

**Comment by lduboeuf** [comment]
hello, thank you for adding my app as a demo.
If it helps, i've also built for `grunt` users the ability to generate template/js files and declarations in html. 
And also for production the ability to load all templates into html respective `<sections>`. 
Did not yet published it to npm: `https://github.com/lduboeuf/grunt-spapp-generator`
